/**
 * The deckbuilder's own tables — see `docs/spec/deckbuilder.md` §3.2. Auth tables (`user`,
 * `session`, `account`, `verification`) live in `auth.schema.ts`, generated by
 * `pnpm run auth:schema` — never hand-edited.
 *
 * A deck's current state is its latest `deck_versions` row by `savedAt`; `decks` itself holds no
 * denormalized copy. `entries` and `legends` are stored as JSON — validated at the application
 * boundary by `#lib/decks/schema.js`, never trusted as typed straight off a read.
 */
import { sql } from 'drizzle-orm';
import {
	type AnySQLiteColumn,
	index,
	integer,
	primaryKey,
	sqliteTable,
	text
} from 'drizzle-orm/sqlite-core';
import type { DeckEntryPayload } from '#lib/decks/schema.js';
import { user } from './auth.schema.js';

const now = sql`(cast(unixepoch('subsecond') * 1000 as integer))`;

/** A user's own grouping of their decks (`.scratch/decklist-folders/map.md`) — independent of
 * deck visibility. `parentFolderId` is an unused seam for real nesting later: v1 UI never sets
 * it to non-null, but the column exists so upgrading to nesting is a UI/validation change, not
 * a migration. No `public` visibility tier — folders are never discoverable/browsable, only
 * shareable via a direct `unlisted` link. */
export const deckFolders = sqliteTable(
	'deck_folders',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		ownerId: text('owner_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		visibility: text('visibility', { enum: ['private', 'unlisted'] })
			.notNull()
			.default('private'),
		parentFolderId: text('parent_folder_id').references(
			(): AnySQLiteColumn => deckFolders.id,
			{ onDelete: 'set null' }
		),
		createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [index('deck_folders_owner_idx').on(table.ownerId)]
);

export const decks = sqliteTable(
	'decks',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		ownerId: text('owner_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		visibility: text('visibility', { enum: ['public', 'unlisted', 'private'] })
			.notNull()
			.default('private'),
		createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().default(now),
		/**
		 * One of the game's official Starter Decks. No admin UI sets this — a one-off script
		 * does, for the handful of decks it'll ever apply to — so it's the script's job to also
		 * force `visibility = 'public'` in that same update; nothing here enforces the pairing.
		 */
		isStarterDeck: integer('is_starter_deck', { mode: 'boolean' }).notNull().default(false),
		/** Zero-or-one — a deck belongs to at most one folder, mirroring common folder (not tag)
		 * conventions. `set null` on folder delete: deleting a folder un-groups its decks rather
		 * than deleting them. */
		folderId: text('folder_id').references(() => deckFolders.id, { onDelete: 'set null' })
	},
	(table) => [index('decks_owner_idx').on(table.ownerId), index('decks_folder_idx').on(table.folderId)]
);

export const deckVersions = sqliteTable(
	'deck_versions',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		deckId: text('deck_id')
			.notNull()
			.references(() => decks.id, { onDelete: 'cascade' }),
		/** See `#lib/decks/schema.js` — validated there, not trusted as typed straight off a read. */
		entries: text('entries', { mode: 'json' }).notNull().$type<DeckEntryPayload[]>(),
		/** Up to 3 Legend card slugs. */
		legends: text('legends', { mode: 'json' }).notNull().$type<string[]>(),
		savedAt: integer('saved_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [index('deck_versions_deck_saved_idx').on(table.deckId, table.savedAt)]
);

/** One row per (deck, user) — enforced by the primary key, not just an application check. */
export const deckLikes = sqliteTable(
	'deck_likes',
	{
		deckId: text('deck_id')
			.notNull()
			.references(() => decks.id, { onDelete: 'cascade' }),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		likedAt: integer('liked_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [primaryKey({ columns: [table.deckId, table.userId] })]
);

export * from './auth.schema.js';
