/**
 * The deckbuilder's own tables — see `docs/spec/deckbuilder.md` §3.2. Auth tables (`user`,
 * `session`, `account`, `verification`) live in `auth.schema.ts`, generated by
 * `pnpm run auth:schema` — never hand-edited.
 *
 * A deck's current state is its latest `deck_versions` row by `savedAt`; `decks` itself holds no
 * denormalized copy. `entries` and `legends` are stored as JSON — validated at the application
 * boundary by `#lib/decks/schema.js`, never trusted as typed straight off a read.
 */
import { sql } from 'drizzle-orm';
import {
	type AnySQLiteColumn,
	index,
	integer,
	primaryKey,
	sqliteTable,
	text
} from 'drizzle-orm/sqlite-core';
import type { DeckEntryPayload } from '#lib/decks/schema.js';
import { user } from './auth.schema.js';

const now = sql`(cast(unixepoch('subsecond') * 1000 as integer))`;

/** A user's own grouping of their decks (`.scratch/decklist-folders/map.md`) — independent of
 * deck visibility. `parentFolderId` is an unused seam for real nesting later: v1 UI never sets
 * it to non-null, but the column exists so upgrading to nesting is a UI/validation change, not
 * a migration. No `public` visibility tier — folders are never discoverable/browsable, only
 * shareable via a direct `shared` link. */
export const deckFolders = sqliteTable(
	'deck_folders',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		ownerId: text('owner_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		/** `shared`, not `unlisted`: "unlisted" only means something by contrast with a public tier,
		 * and folders have none — see `CONTEXT.md`'s Unlisted vs Shared entries. */
		visibility: text('visibility', { enum: ['private', 'shared'] })
			.notNull()
			.default('private'),
		parentFolderId: text('parent_folder_id').references(
			(): AnySQLiteColumn => deckFolders.id,
			{ onDelete: 'set null' }
		),
		createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [index('deck_folders_owner_idx').on(table.ownerId)]
);

export const decks = sqliteTable(
	'decks',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		ownerId: text('owner_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		visibility: text('visibility', { enum: ['public', 'unlisted', 'private'] })
			.notNull()
			.default('private'),
		createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().default(now),
		/**
		 * One of the game's official Starter Decks. No admin UI sets this — a one-off script
		 * does, for the handful of decks it'll ever apply to — so it's the script's job to also
		 * force `visibility = 'public'` in that same update; nothing here enforces the pairing.
		 */
		isStarterDeck: integer('is_starter_deck', { mode: 'boolean' }).notNull().default(false),
		/** Zero-or-one — a deck belongs to at most one folder, mirroring common folder (not tag)
		 * conventions. `set null` on folder delete: deleting a folder un-groups its decks rather
		 * than deleting them. */
		folderId: text('folder_id').references(() => deckFolders.id, { onDelete: 'set null' })
	},
	(table) => [index('decks_owner_idx').on(table.ownerId), index('decks_folder_idx').on(table.folderId)]
);

export const deckVersions = sqliteTable(
	'deck_versions',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		deckId: text('deck_id')
			.notNull()
			.references(() => decks.id, { onDelete: 'cascade' }),
		/** See `#lib/decks/schema.js` — validated there, not trusted as typed straight off a read. */
		entries: text('entries', { mode: 'json' }).notNull().$type<DeckEntryPayload[]>(),
		/** Up to 3 Legend card slugs. */
		legends: text('legends', { mode: 'json' }).notNull().$type<string[]>(),
		savedAt: integer('saved_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [index('deck_versions_deck_saved_idx').on(table.deckId, table.savedAt)]
);

/**
 * A user's **Collection** — what they own, one quantity per Printing
 * (`docs/adr/0003-the-collection-is-flat-and-binders-are-showcases.md`).
 *
 * Flat and singular: there is no `collections` table, because a Collection is exactly one per user,
 * unnamed, never created or deleted, and never shared. Binders do **not** partition this — a
 * Printing is never in a Binder instead of here, and an Owned Count is a single column read rather
 * than a sum across containers.
 *
 * Keyed on `printingId` (the UUID) rather than a collector number, per ADR 0001's reasoning:
 * collector numbers are only unique within a Set and are renumbered on reprint.
 *
 * A quantity of zero is not stored. Owning none of a Printing is the absence of a row, so the
 * table only ever holds facts — see `setQuantity` in `collection.ts`, which deletes at zero.
 */
export const collectionItems = sqliteTable(
	'collection_items',
	{
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		printingId: text('printing_id').notNull(),
		quantity: integer('quantity').notNull(),
		updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	// Primary key only, no separate owner index: SQLite's composite PK already indexes
	// `user_id` leftmost, which is what every query here filters on. Same shape as `deck_likes`.
	(table) => [primaryKey({ columns: [table.userId, table.printingId] })]
);

/**
 * A user's **Collecting Goal** — which Printing Runs they are trying to collect, and therefore
 * what "Complete" means for them (`CONTEXT.md`).
 *
 * One row per user, and **JSON rather than a row per Run**. This is the `deck_versions` precedent
 * rather than the `collection_items` one, and the deciding factor is the access pattern: a Goal is
 * read whole on every collection view, written whole when the editor is saved, and never queried
 * by element. There are at most seventeen Runs today, so the blob is a few hundred bytes.
 *
 * Absence is meaningful: **no row means the default Goal** (English retail, every Set — see
 * `DEFAULT_GOAL` in `#lib/collection/goal.ts`). So a user who never opens the editor costs no
 * write, and the default can be changed later without a data migration.
 *
 * Validated at the application boundary like `deck_versions.entries` — never trusted as typed
 * straight off a read, because a stale Run key can outlive a re-ingest.
 */
export const collectingGoals = sqliteTable('collecting_goals', {
	userId: text('user_id')
		.primaryKey()
		.references(() => user.id, { onDelete: 'cascade' }),
	/** Printing Run keys — `<setId>|<treatment>|<locale>`. See `runKey` in `#lib/collection/goal.ts`. */
	runs: text('runs', { mode: 'json' }).notNull().$type<string[]>(),
	updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull().default(now)
});

/** One row per (deck, user) — enforced by the primary key, not just an application check. */
export const deckLikes = sqliteTable(
	'deck_likes',
	{
		deckId: text('deck_id')
			.notNull()
			.references(() => decks.id, { onDelete: 'cascade' }),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		likedAt: integer('liked_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [primaryKey({ columns: [table.deckId, table.userId] })]
);

export * from './auth.schema.js';
