/**
 * The deckbuilder's own tables — see `docs/spec/deckbuilder.md` §3.2. Auth tables (`user`,
 * `session`, `account`, `verification`) live in `auth.schema.ts`, generated by
 * `pnpm run auth:schema` — never hand-edited.
 *
 * A deck's current state is its latest `deck_versions` row by `savedAt`; `decks` itself holds no
 * denormalized copy. `entries` and `legends` are stored as JSON — validated at the application
 * boundary by `#lib/decks/schema.js`, never trusted as typed straight off a read.
 */
import { sql } from 'drizzle-orm';
import {
	type AnySQLiteColumn,
	index,
	integer,
	primaryKey,
	sqliteTable,
	text
} from 'drizzle-orm/sqlite-core';
import type { DeckEntryPayload } from '#lib/decks/schema.js';
import { user } from './auth.schema.js';

const now = sql`(cast(unixepoch('subsecond') * 1000 as integer))`;

/** A user's own grouping of their decks (`.scratch/decklist-folders/map.md`) — independent of
 * deck visibility. `parentFolderId` is an unused seam for real nesting later: v1 UI never sets
 * it to non-null, but the column exists so upgrading to nesting is a UI/validation change, not
 * a migration. No `public` visibility tier — folders are never discoverable/browsable, only
 * shareable via a direct `shared` link. */
export const deckFolders = sqliteTable(
	'deck_folders',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		ownerId: text('owner_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		/** `shared`, not `unlisted`: "unlisted" only means something by contrast with a public tier,
		 * and folders have none — see `CONTEXT.md`'s Unlisted vs Shared entries. */
		visibility: text('visibility', { enum: ['private', 'shared'] })
			.notNull()
			.default('private'),
		parentFolderId: text('parent_folder_id').references((): AnySQLiteColumn => deckFolders.id, {
			onDelete: 'set null'
		}),
		createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [index('deck_folders_owner_idx').on(table.ownerId)]
);

export const decks = sqliteTable(
	'decks',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		ownerId: text('owner_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		visibility: text('visibility', { enum: ['public', 'unlisted', 'private'] })
			.notNull()
			.default('private'),
		createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().default(now),
		/**
		 * One of the game's official Starter Decks. No admin UI sets this — a one-off script
		 * does, for the handful of decks it'll ever apply to — so it's the script's job to also
		 * force `visibility = 'public'` in that same update; nothing here enforces the pairing.
		 */
		isStarterDeck: integer('is_starter_deck', { mode: 'boolean' }).notNull().default(false),
		/** Zero-or-one — a deck belongs to at most one folder, mirroring common folder (not tag)
		 * conventions. `set null` on folder delete: deleting a folder un-groups its decks rather
		 * than deleting them. */
		folderId: text('folder_id').references(() => deckFolders.id, { onDelete: 'set null' })
	},
	(table) => [
		index('decks_owner_idx').on(table.ownerId),
		index('decks_folder_idx').on(table.folderId)
	]
);

export const deckVersions = sqliteTable(
	'deck_versions',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		deckId: text('deck_id')
			.notNull()
			.references(() => decks.id, { onDelete: 'cascade' }),
		/** See `#lib/decks/schema.js` — validated there, not trusted as typed straight off a read. */
		entries: text('entries', { mode: 'json' }).notNull().$type<DeckEntryPayload[]>(),
		/** Up to 3 Legend card slugs. */
		legends: text('legends', { mode: 'json' }).notNull().$type<string[]>(),
		/** The 7-card sideboard. Defaults to `[]`, which is both what every row written before this
		 * column existed means and a legal deck in its own right — see `sideboardStatus`. */
		sideboard: text('sideboard', { mode: 'json' })
			.notNull()
			.default([])
			.$type<DeckEntryPayload[]>(),
		savedAt: integer('saved_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [index('deck_versions_deck_saved_idx').on(table.deckId, table.savedAt)]
);

/**
 * A user's **Collection** — what they own, one quantity per Printing
 * (`docs/adr/0003-the-collection-is-flat-and-binders-are-showcases.md`).
 *
 * Flat and singular: there is no `collections` table, because a Collection is exactly one per user,
 * unnamed, never created or deleted, and never shared. Binders do **not** partition this — a
 * Printing is never in a Binder instead of here, and an Owned Count is a single column read rather
 * than a sum across containers.
 *
 * Keyed on `printingId` (the UUID) rather than a collector number, per ADR 0001's reasoning:
 * collector numbers are only unique within a Set and are renumbered on reprint.
 *
 * A quantity of zero is not stored. Owning none of a Printing is the absence of a row, so the
 * table only ever holds facts — see `setQuantity` in `collection.ts`, which deletes at zero.
 */
export const collectionItems = sqliteTable(
	'collection_items',
	{
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		printingId: text('printing_id').notNull(),
		quantity: integer('quantity').notNull(),
		updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	// Primary key only, no separate owner index: SQLite's composite PK already indexes
	// `user_id` leftmost, which is what every query here filters on. Same shape as `deck_likes`.
	(table) => [primaryKey({ columns: [table.userId, table.printingId] })]
);

/**
 * A user's **Collecting Goal** — which Printing Runs they are trying to collect, and therefore
 * what "Complete" means for them (`CONTEXT.md`).
 *
 * One row per user, and **JSON rather than a row per Run**. This is the `deck_versions` precedent
 * rather than the `collection_items` one, and the deciding factor is the access pattern: a Goal is
 * read whole on every collection view, written whole when the editor is saved, and never queried
 * by element. There are at most seventeen Runs today, so the blob is a few hundred bytes.
 *
 * Absence is meaningful: **no row means the default Goal** (English retail, every Set — see
 * `DEFAULT_GOAL` in `#lib/collection/goal.ts`). So a user who never opens the editor costs no
 * write, and the default can be changed later without a data migration.
 *
 * Validated at the application boundary like `deck_versions.entries` — never trusted as typed
 * straight off a read, because a stale Run key can outlive a re-ingest.
 */
export const collectingGoals = sqliteTable('collecting_goals', {
	userId: text('user_id')
		.primaryKey()
		.references(() => user.id, { onDelete: 'cascade' }),
	/** Printing Run keys — `<setId>|<treatment>|<locale>`. See `runKey` in `#lib/collection/goal.ts`. */
	runs: text('runs', { mode: 'json' }).notNull().$type<string[]>(),
	updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull().default(now)
});

/**
 * The shared parent for a user's **named** lists of Printings — Binders and Wantlists
 * (`CONTEXT.md`, and `docs/adr/0003-the-collection-is-flat-and-binders-are-showcases.md`).
 *
 * One table because naming, visibility, ownership checks and share links are identical for both.
 * Their *entries* are not, and so are not shared: a Binder's are positional and carry no
 * quantity, a Wantlist's are unordered and carry a target quantity. An earlier design put both in
 * one entries table; that only worked while both were "a name plus a quantity per Printing".
 *
 * Named `printing_lists` rather than `binders` so neither child has to live under a table whose
 * name describes the other. The Collection is deliberately **not** here: it is unnamed, singular
 * and unshareable, so it has nothing this table offers.
 */
export const printingLists = sqliteTable(
	'printing_lists',
	{
		id: text('id')
			.primaryKey()
			.$defaultFn(() => crypto.randomUUID()),
		ownerId: text('owner_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		kind: text('kind', { enum: ['binder', 'wantlist'] }).notNull(),
		name: text('name').notNull(),
		/** `shared`, not `unlisted`: there is no public tier to be unlisted from. */
		visibility: text('visibility', { enum: ['private', 'shared'] })
			.notNull()
			.default('private'),
		/**
		 * The one list of this kind that other surfaces add to without asking — the Wantlist the
		 * collection view fills, today.
		 *
		 * A column rather than a client preference, because "which list am I filling" is a fact
		 * about the user, not about the browser they happen to be sitting at; and a flag on the row
		 * rather than a pointer on `user`, because that way it is impossible to designate a list
		 * that doesn't exist or belongs to someone else. At most one per (owner, kind) is an
		 * application invariant, enforced by `setDefaultList` clearing the others in the same batch
		 * — SQLite can't express "at most one true per group" as a constraint.
		 */
		isDefault: integer('is_default', { mode: 'boolean' }).notNull().default(false),
		createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [index('printing_lists_owner_kind_idx').on(table.ownerId, table.kind)]
);

/**
 * One **Pocket** — a slot on a Binder Page holding at most one Printing (`CONTEXT.md`).
 *
 * **No quantity column, deliberately.** A Pocket displays a card; "showing off three copies" is
 * not a thing, and the absence is what makes it impossible to express the contradiction
 * cyberdecktools allows, where a binder claims more copies than the collection holds.
 *
 * `(list_id, page, pocket)` is the key, so a Pocket is addressable and a Page can have deliberate
 * gaps — an empty Pocket is simply a row that does not exist, which is the one place absence is
 * the right encoding: there is nothing to say about a held space beyond where it is.
 *
 * `printing_id` has no foreign key, matching `collection_items`: printings live in a build-time
 * artifact, not a table.
 */
export const binderPockets = sqliteTable(
	'binder_pockets',
	{
		listId: text('list_id')
			.notNull()
			.references(() => printingLists.id, { onDelete: 'cascade' }),
		/** Zero-based, contiguous. A Binder always has at least page 0. */
		page: integer('page').notNull(),
		/** Zero-based position within the page — nine per page today. */
		pocket: integer('pocket').notNull(),
		printingId: text('printing_id').notNull()
	},
	(table) => [primaryKey({ columns: [table.listId, table.page, table.pocket] })]
);

/**
 * One entry on a **Wantlist** — a Printing the owner is looking for, and how many (`CONTEXT.md`).
 *
 * The deliberate opposite of a Pocket. A Wantlist is unordered, so there is no position column and
 * `(list_id, printing_id)` is the key; and it carries a **target quantity**, because "I need three
 * of these" is the whole point of asking. Absence means not wanted — a zero-quantity entry is
 * deleted rather than stored, the same rule `collection_items` follows.
 *
 * `printing_id` has no foreign key, matching `collection_items` and `binder_pockets`: printings
 * live in a build-time artifact, not a table.
 */
export const wantlistEntries = sqliteTable(
	'wantlist_entries',
	{
		listId: text('list_id')
			.notNull()
			.references(() => printingLists.id, { onDelete: 'cascade' }),
		printingId: text('printing_id').notNull(),
		/** How many copies the owner is after. At least 1 — zero deletes the row. */
		quantity: integer('quantity').notNull(),
		/** Free text, for the one thing a Wantlist needs that a Collection doesn't: why. */
		note: text('note'),
		updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	// Primary key only: it already indexes `list_id` leftmost, which is what every query filters on.
	(table) => [primaryKey({ columns: [table.listId, table.printingId] })]
);

/** One row per (deck, user) — enforced by the primary key, not just an application check. */
export const deckLikes = sqliteTable(
	'deck_likes',
	{
		deckId: text('deck_id')
			.notNull()
			.references(() => decks.id, { onDelete: 'cascade' }),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		likedAt: integer('liked_at', { mode: 'timestamp_ms' }).notNull().default(now)
	},
	(table) => [primaryKey({ columns: [table.deckId, table.userId] })]
);

export * from './auth.schema.js';
